let names = [
    'Cemento gris',
    'Arenaderio',
    'Grava',
    'Malla electro soldada 6-6/10-10',
    'Manguera p-al-p de 1/2" para agua potable',
    'Valvula de seguridad magnetica de 1/2" de diam.',
    'Conectores macho de bronce de 1/2 de diam.',
    'Conectores embre de bronce de 1/2 de diam.',
    'Adaptador de bronce de 1/2 de diametro',
    'Abrazaderas in de 1/2 de diametro',
    'Tee galvanizada de 1/2 de diametro',
    'Gusanos galvanizados de 1/2 de diametro',
    'Cople galvanizado de 1/2 de diametro',
    'Abrazadera hidrotoma pvc de 2"x1/2" de diametro',
    'Sujetador insercion para tubo pe-al-pe de 1/2" de diametro',
    'Tubo pvc sanitario de 6" de diametro',
    'Codo galvanizado de 1/2 de diametro',
    'Registro de concreto armado para toma domiciliaria (70cm x 30cm)',
    'Abrazadera hidrotoma de fierro de  1 1/2"x1/2" de diametro',
    'Abrazadera hidrotoma de fierro de 2"x1/2" de diametro',
    'Abrazadera hidrotoma de fierro de 3"x1/2" de diametro',
    'Abrazadera hidrotoma de fierro de 3"x1/2"',
    'Abrazadera hidrotoma de fierro de 4"x1/2" de diametro',
    'Abrazadera hidrotoma de fierro de 6"x1/2" de diametro',
    'Abrazadera hidrotoma de pvc de 1 1/2"x1/2" de diametro ',
    'Abrazadera hidrotoma de pvc de 2"x1/2" de diametro ',
    'Abrazadera hidrotoma de pvc de 2 1/2"x1/2" de diametro ',
    'Abrazadera hidrotoma de pvc de 3"x1/2" de diametro ',
    'Abrazadera hidrotoma de pvc de 4"x1/2" de diametro ',
    'Abrazadera hidrotoma de pvc de 6"x1/2" de diametro ',
    'Abrazadera hidrotoma de pvc de 8"x1/2" de diametro ',
    'Abrazadera hidrotoma de pvc de 10"x1/2" de diametro ',
    'Cople galvanizado de 1" de diam.',
    'Gusano galvanizado de 1" de diam.',
    'Micromedidor tipo volumetrico de chorro multiple de 1/2"',
    'Valvula de admision y expulsion de aire de 1/2" de diam.',
    'Caja p/medidor polietileno para agua potable',
    'Tubo p.v.c. hidraulico anger rd 26 de 38 mm',
    'Tubop.v.c. hidraulico anger  rd 26 de 51 mm',
    'Tubo p.v.c. hidraulico anger  rd 26 de 64 mm',
    'Tubo p.v.c. hidraulico anger  rd 26 de 75 mm',
    'Tubop.v.c. hidraulico anger  rd 26 de 100 mm',
    'Tubo p.v.c. hidraulico anger  rd 26 de 150 mm',
    'Tubop.v.c. hidraulico anger  rd 26 de 200 mm',
    'Anillode hule para p.v.c. hidraulica de 38 mm',
    'Anillo de hule para p.v.c. hidraulica de 51 mm',
    'Anillo de hule para p.v.c. hidraulica de 64 mm',
    'Anillo de hule para p.v.c. hidraulica de 75 mm',
    'Anillo de hule para p.v.c. hidraulica de 100 mm',
    'Anillo de hule para p.v.c. hidraulica de 150 mm',
    'Anillo de hule para p.v.c. hidraulica de 200 mm',
    'Tapon campana p.v.c. hidraulico de 51 mm',
    'Tapon campana p.v.c. hidraulico de 64 mm',
    'Tapon campana p.v.c. hidraulico de 75 mm',
    'Tapon campana p.v.c. hidraulico de 100 mm',
    'Tapon campana p.v.c. hidraulico de 150 mm',
    'Tapon campana p.v.c. hidraulico de 200 mm',
    'Tapon espiga p.v.c. hidraulico de 38 mm',
    'Tapon espiga p.v.c. hidraulico de 51 mm',
    'Tapon espiga p.v.c. hidraulico de 64 mm',
    'Tapon espiga p.v.c. hidraulico de 75 mm',
    'Tapon espiga p.v.c. hidraulico de 100 mm',
    'Tapon espiga p.v.c. hidraulico de 150 mm',
    'Tapon espiga p.v.c. hidraulico de 200 mm',
    'Adaptador campana p.v.c. hidraulico de 38 mm',
    'Adaptador campana p.v.c. hidraulico de 51 mm',
    'Adaptador campana p.v.c. hidraulico de 64 mm',
    'Adaptador campana p.v.c. hidraulico de 75 mm',
    'Adaptador campana p.v.c. hidraulico de 100 mm',
    'Adaptador campana p.v.c. hidraulico de 150 mm',
    'Adaptador espiga p.v.c. hidraulico de 38 mm',
    'Adaptadorespiga p.v.c. hidraulico de 51 mm',
    'Adaptador espiga p.v.c. hidraulico de 64 mm',
    'Adaptador espiga p.v.c. hidraulico de 75 mm',
    'Adaptador espiga p.v.c. hidraulico de 100 mm',
    'Adaptador espiga p.v.c. hidraulico de 150 mm',
    'Extremidad campana p.v.c. hidraulica de 38 mm',
    'Extremidad campana p.v.c. hidraulica de 51 mm',
    'Extremidad campana p.v.c. hidraulica de 64 mm',
    'Extremidad campana p.v.c. hidraulica de 75 mm',
    'Extremidad campana p.v.c. hidraulica de 100 mm',
    'Extremidad campana p.v.c. hidraulica de 150 mm',
    'Extremidad campana p.v.c. hidraulica de 200 mm',
    'Extremidad espiga p.v.c. hidraulica de 38 mm',
    'Extremidad espiga p.v.c. hidraulica de 51 mm',
    'Extremidad espiga p.v.c. hidraulica de 64 mm',
    'Extremidad espiga p.v.c. hidraulica de 75 mm',
    'Extremidad espiga p.v.c. hidraulica de 100 mm',
    'Extremidad espiga p.v.c. hidraulica de 150 mm',
    'Extremidad espiga p.v.c. hidraulica de 200 mm',
    'Reduccion campana p.v.c. hidraulica de 51 x 38 mm',
    'Reduccion campana p.v.c. hidraulica de 64 x 51 mm',
    'Reduccion campana p.v.c. hidraulica de 75 x 51 mm',
    'Reduccion campana p.v.c. hidraulica de 75 x 64 mm',
    'Reduccion campana  p.v.c. hidraulica de 100 x 50 mm',
    'Reduccion campana p.v.c. hidraulica de 100 x 64 mm',
    'Reduccion campana p.v.c. hidraulica de 100 x 75 mm',
    'Reduccion campana p.v.c. hidraulica de 150 x 64 mm',
    'Reduccion campana p.v.c. hidraulica de 150 x 100 mm',
    'Reduccion campana p.v.c. hidraulica de 200 x 100 mm',
    'Reduccion campana p.v.c. hidraulica de 200 x 150 mm',
    'Reduccion espiga p.v.c. hidraulica de 51 x 38 mm',
    'Reduccion espiga p.v.c. hidraulica de 64 x 51 mm',
    'Reduccion espiga p.v.c. hidraulica de 75 x 51 mm',
    'Reduccion espiga p.v.c. hidraulica de 75 x 64 mm',
    'Reduccion espiga p.v.c. hidraulica de 100 x 51 mm',
    'Reduccion espiga p.v.c. hidraulica de 100 x 64 mm',
    'Reduccion espiga p.v.c. hidraulica de 100 x 75 mm',
    'Reduccion espiga p.v.c. hidraulica de 150 x 100 mm',
    'Reduccion espiga p.v.c. hidraulica de 200 x 150 mm',
    'Tee p.v.c. hidraulica c/c anger de 38 mm',
    'Tee p.v.c. hidraulica c/c anger de 51 mm',
    'Tee p.v.c. hidraulica c/c anger de 64 mm',
    'Tee p.v.c. hidraulica c/c anger de 75 mm',
    'Tee p.v.c. hidraulica c/c anger de 100 mm',
    'Tee p.v.c. hidraulica c/c anger de 150 mm',
    'Tee p.v.c. hidraulica c/c anger de 200 mm',
    'Tee p.v.c. hidraulica c/c anger de 50 x 38 mm',
    'Tee p.v.c. hidraulica c/c anger de 64 x 50 mm',
    'Tee p.v.c. hidraulica c/c anger de 75 x 50 mm',
    'Tee p.v.c. hidraulica c/c anger de 75 x 64 mm',
    'Tee p.v.c. hidraulica c/c anger de 100 x 50 mm',
    'Tee p.v.c. hidraulica c/c anger de 100 x 64 mm',
    'Tee p.v.c. hidraulica c/c anger de 100 x 75 mm',
    'Tee p.v.c. hidraulica c/c anger de 150 x 100 mm',
    'Codo de 22° p.v.c. hidraulica c/c anger de 38 mm',
    'Codode 22° p.v.c. hidraulica c/c anger de 51 mm',
    'Codo de 22° p.v.c. hidraulica c/c anger de 64 mm',
    'Codo de 22° p.v.c. hidraulica c/c anger de 75 mm',
    'Codo de 22° p.v.c. hidraulica c/c anger de 100 mm',
    'Codo de 22° p.v.c. hidraulica c/c anger de 150 mm',
    'Codo de 22° p.v.c. hidraulica c/c anger de 200 mm',
    'Codo de 45° p.v.c. hidraulica c/c anger de 38 mm',
    'Codo de 45° p.v.c. hidraulica c/c anger de 64 mm',
    'Codo de 45° p.v.c. hidraulica c/c anger de 75 mm',
    'Codo de 45° p.v.c. hidraulica c/c anger de 100 mm',
    'Codo de 45° p.v.c. hidraulica c/c anger de 150 mm',
    'Codo de 45° p.v.c. hidraulica c/c anger de 200 mm',
    'Codo de 90° p.v.c. hidraulica c/c anger de 38 mm',
    'Codo de 90° p.v.c. hidraulica c/c anger  de 51 mm',
    'Codo de 90° p.v.c. hidraulica c/c anger de 64 mm',
    'Codo de 90° p.v.c. hidraulica c/c anger de 75 mm',
    'Codo de 90° p.v.c. hidraulica c/c anger de 100 mm',
    'Codo de 90° p.v.c. hidraulica c/c anger de 150 mm',
    'Codo de 90° p.v.c. hidraulica c/c anger de 200 mm',
    'Cople reparacion p.v.c. hidraulico c/c anger de 38 mm',
    'Cople reparacion p.v.c. hidraulico c/c anger de 51 mm',
    'Cople reparacion p.v.c. hidraulico c/c anger de 64 mm',
    'Cople reparacion p.v.c. hidraulico c/c anger de 75 mm',
    'Cople reparacion p.v.c. hidraulico c/c anger de 100 mm',
    'Cople reparacion p.v.c. hidraulico c/c anger de 150 mm',
    'Cople reparacion p.v.c. hidraulico c/c anger de 200 mm',
    'Cruz p.v.c. hidraulica c/c anger de 38 x 38 mm',
    'Cruz p.v.c. hidraulica c/c anger de 50 x 38 mm',
    'Cruz p.v.c. hidraulica c/c anger de 50 x 50 mm',
    'Cruz p.v.c. hidraulica c/c anger de 60 x 50 mm',
    'Cruz p.v.c. hidraulica c/c anger de 64 x 64 mm',
    'Cruz p.v.c. hidraulica c/c anger de 75 x 50 mm',
    'Cruz p.v.c. hidraulica c/c anger de 75 x 64 mm',
    'Cruz p.v.c. hidraulica c/c anger de 75 x 75 mm',
    'Cruz p.v.c. hidraulica c/c anger de 100 x 50 mm',
    'Cruz p.v.c. hidraulica c/c anger de 100 x 64 mm',
    'Cruz p.v.c. hidraulica c/c anger de 100 x 75 mm',
    'Cruz p.v.c. hidraulica c/c anger de 100 x 100 mm',
    'Cruz p.v.c. hidraulica c/c anger de 150 x 100 mm',
    'Cruz p.v.c. hidraulica c/c anger de 150 x 150 mm',
    'Cruz p.v.c. hidraulica c/c anger de 200 x 200 mm',
    'Empaque de plomo de 2" diametro',
    'Empaque de plomo de 2 1/2" diametro',
    'Empaque de plomo de 3" de diametro',
    'Empaque de plomo de 4" de diametro',
    'Empaque de plomo de 6" de diametro',
    'Empaque de plomo de 8" de diametro',
    'Empaque de neopreno de 2" diametro',
    'Empaque de neopreno de 2 1/2 de diametro',
    'Empaque de neopreno de 3" de diametro',
    'Empaque de neopreno de 4" de diametro',
    'Empaque de neopreno de 6" de diametro',
    'Empaque de neopreno de 8" de diametro',
    'Junta giubault de 2" de diametro',
    'Junta giubault de 2 1/2" de diametro',
    'Junta giubault de 3" de diametro',
    'Junta giubault de 4" de diametro',
    'Junta giubault de 6" de diametro',
    'Junta giubault de 8" de diametro',
    'Tornillo con cabeza y tuerca hexagonal de 5/8" x 2 1/2"',
    'Tornillo con cabeza y tuerca hexagonal de 5/8" x 3" ',
    'Tornillo con cabeza y tuerca hexagonal de 5/8" x 4 1/2"',
    'Tornillo con cabeza y tuerca hexagonal de 3/4" x 3 1/2"',
    'Tee fo fo bridada de 2" x 2"',
    'Tee fo fo bridada de 2 1/2" x 2"',
    'Tee fo fo bridada de 2 1/2" x 2 1/2"',
    'Tee fo fo bridada de 3" x 2"',
    'Tee fo fo bridada de 3" x 2 1/2"',
    'Tee fo fo bridada de 3" x 3"',
    'Tee fo fo bridada de 4" x 2"',
    'Tee fo fo bridada de 4" x 2 1/2"',
    'Tee fo fo bridada de 4" x 3"',
    'Tee fo fo bridada de 4" x 4"',
    'Tee fo fo bridada de 6" x 2"',
    'Tee fo fo bridada de 6" x 2 1/2"',
    'Tee fo fo bridada de 6" x 3"',
    'Tee fo fo bridada de 6" x 4"',
    'Tee fo fo bridada de 6" x 6"',
    'Tee fo fo bridada de 8" x 2"',
    'Tee fo fo bridada de 8" x 2 1/2"',
    'Tee fo fo bridada de 8" x 3"',
    'Tee fo fo bridada de 8" x 4"',
    'Tee fo fo bridada de 8" x 6"',
    'Tee fo fo bridada de 8" x 8"',
    'Reduccion de fo fo bridada de 2 1/2" x 2"',
    'Reduccion de fo fo bridada de 3" x 2"',
    'Reduccion de fo fo bridada de 3" x 2 1/2"',
    'Reduccion de fo fo bridada de 4" x 2"',
    'Reduccion de fo fo bridada de 4" x 2 1/2"',
    'Reduccion de fo fo bridada de 4" x 3"',
    'Reduccion de fo fo bridada de 6" x 2"',
    'Reduccion de fo fo bridada de 6" x 2 1/2"',
    'Reduccion de fo fo bridada de 6" x 3"',
    'Reduccion de fo fo bridada de 6" x 4"',
    'Reduccion de fo fo bridada de 8" x 2"',
    'Reduccion de fo fo bridada de 8" x 2 1/2"',
    'Reduccion de fo fo bridada de 8" x 3"',
    'Reduccion de fo fo bridada de 8" x 4"',
    'Reduccion de fo fo bridada de 8" x 6"',
    'Extremidad de fo fo (a14) bridada de 2"',
    'Extremidad de fo fo (a14) bridada de 2 1/2"',
    'Extremidad de fo fo (a14) bridada de 3"',
    'Extremidad de fo fo (a14) bridada de 4"',
    'Extremidad de fo fo (a14) bridada de 6"',
    'Extremidad de fo fo (a14) bridada de 8"',
    'Carrete de fo fo bridado de 2" x 25 cm',
    'Carrete de fo fo bridado de 2 1/2" x 25 cm',
    'Carrete de fo fo bridado de 3" x 25 cm',
    'Carrete de fo fo bridado de 4" x 25 cm',
    'Carrete de fo fo bridado de 6" x 25 cm',
    'Carrete de fo fo bridado de 8" x 25 cm',
    'Carrete de fo fo bridado de 2" x 50 cm',
    'Carrete de fo fo bridado de 2 1/2" x 50 cm',
    'Carrete de fo fo bridado de 3" x 50 cm',
    'Carrete de fo fo bridado de 4" x 50 cm',
    'Carrete de fo fo bridado de 6" x 50 cm',
    'Carrete de fo fo bridado de 8" x 50 cm',
    'Cruz de fo fo bridada de 2" x 2"',
    'Cruz de fo fo bridada de 2 1/2" x 2"',
    'Cruz de fo fo bridada de 2 1/2" x 2 1/2"',
    'Cruz de fo fo bridada de 3" x 2"',
    'Cruz de fo fo bridada de 3" x 2 1/2"',
    'Cruz de fo fo bridada de 3" x 3"',
    'Cruz de fo fo bridada de 4" x 2"',
    'Cruz de fo fo bridada de 4" x 2 1/2"',
    'Cruz de fo fo bridada de 4" x 3"',
    'Cruz de fo fo bridada de 4" x 4"',
    'Cruz de fo fo bridada de 6" x 2"',
    'Cruz de fo fo bridada de 6" x 2 1/2"',
    'Cruz de fo fo bridada de 6" x 3"',
    'Cruz de fo fo bridada de 6" x 4"',
    'Cruz de fo fo bridada de 6" x 6"',
    'Cruz de fo fo bridada de 8" x 2"',
    'Cruz de fo fo bridada de 8" x 2 1/2"',
    'Cruz de fo fo bridada de 8" x 3"',
    'Cruz de fo fo bridada de 8" x 4"',
    'Cruz de fo fo bridada de 8" x 6"',
    'Cruz de fo fo bridada de 8" x 8"',
    'Brida roscada de fofo de 2" de diam',
    'Brida roscada de fofo de 2 1/2" de diam',
    'Brida roscada de fofo de 3" de diam',
    'Brida roscada de fofo de 4" de diam',
    'Brida roscada de fofo de 6" de diam',
    'Brida roscada de fo fo de 8" de diam',
    'Tapa ciega bridada de fofo de 2" de diam',
    'Tapa ciega bridada de fofo de 2 1/2" de diam',
    'Tapa ciega bridada de fofo de 3" de diam',
    'Tapa ciega bridada de fofo de 4" de diam',
    'Tapa ciega bridada de fofo de 6" de diam',
    'Tapa ciega bridada de fofo de 8" de diam',
    'Codo de 90° de fo fo bridado de 2"',
    'Codo de 90° de fo fo bridado de 2 1/2"',
    'Codo de 90° de fo fo bridado de 3"',
    'Codo de 90° de fo fo bridado de 4"',
    'Codo de 90° de fo fo bridado de 6"',
    'Codo de 90° de fo fo bridado de 8"',
    'Codo de 45° de fo fo bridado de 2"',
    'Codo de 45° de fo fo bridado de 2 1/2"',
    'Codo de 45° de fo fo bridado de 3"',
    'Codo de 45° de fo fo bridado de 4"',
    'Codo de 45° de fo fo bridado de 6"',
    'Codo de 45° de fo fo bridado de 8"',
    'Junta universal de 2" de diametro',
    'Junta universal de 2 1/2" de diametro',
    'Junta universal de 3" de diametro',
    'Junta universal de 4" de diametro',
    'Junta universal de 6" de diametro',
    'Junta universal de 8" de diametro',
    'Valvula de compuerta bridada de 125 psi de 2"',
    'Valvula de compuerta bridada de 125 psi de 2 1/2"',
    'Valvula de compuerta bridada de 125 psi de 3"',
    'Valvula de compuerta bridada de 125 psi de 4"',
    'Valvula de compuerta bridada de 125 psi de 6"',
    'Valvula de compuerta bridada de 125 psi de 8"',
    'Valvula de globo de rosca, bronce 125 psi de 1/2"',
    'Valvula de globo de rosca, bronce 125 psi de 3/4"',
    'Valvula de globo de rosca, bronce 125 psi de 1"',
    'Valvula de globo de rosca, bronce 125 psi de 1 1/2"',
    'Valvula de globo de rosca, bronce 125 psi de 2"',
    'Valvula de globo de rosca, bronce 125 psi de 2 1/2"',
    'Valvula de globo de rosca, bronce 125 psi de 3"',
    'Valvula de globo de rosca, bronce 125 psi de 4"',
    'Contramarco sencillo de 0.90 m. con canal de 4"',
    'Contramarco sencillo de 1.00 m. con canal de 4"',
    'Contramarco sencillo de 1.10 m. con canal de 4"',
    'Contramarco sencillo de 1.40 m. con canal de 4"',
    'Contramarco sencillo de 1.40 m. con canal de 6"',
    'Contramarco sencillo de 1.80 m. con canal de 4"',
    'Contramarco sencillo de 1.80 m. con canal de 6"',
    'Contramarco doble de 1.80 m. con canal de 4"',
    'Contramarco doble de 1.80 m. con canal de 6"',
    'Tubo galvanizado cedula 40 de 13 mm',
    'Tubo galvanizado cedula 40 de 19 mm',
    'Tubo galvanizado cedula 40 de 25 mm',
    'Tubo galvanizado cedula 40 de 32 mm',
    'Tubo galvanizado cedula 40 de 38 mm',
    'Tubo galvanizado cedula 40 de 51 mm',
    'Tubo galvanizado cedula 40 de 64 mm',
    'Tubo galvanizado cedula 40 de 75 mm',
    'Tubo galvanizado cedula 40 de 100 mm',
    'Tubo galvanizado cedula 40 de 150 mm',
    'Tapon capa galvanizado de 13 mm',
    'Tapon capa galvanizado de 19 mm',
    'Tapon capa galvanizado de 25 mm',
    'Tapon capa galvanizado de 32 mm',
    'Tapon capa galvanizado de 38 mm',
    'Tapon capa galvanizado de 51 mm',
    'Tapon capa galvanizado de 64 mm',
    'Tapon capa galvanizado de 75 mm',
    'Tapon capa galvanizado de 100 mm',
    'Tapon macho galvanizado de 13 mm',
    'Tapon macho galvanizado de 19 mm',
    'Tapon macho galvanizado de 25 mm',
    'Tapon macho galvanizado de 32 mm',
    'Tapon macho galvanizado de 38 mm',
    'Tapon macho galvanizado de 51 mm',
    'Tapon macho galvanizado de 64 mm',
    'Tapon macho galvanizado de 75 mm',
    'Tapon macho galvanizado de 100 mm',
    'Reduccion bushing galvanizado de 19 mm a 13 mm',
    'Reduccion bushing galvanizado de 25 mm a 13 mm',
    'Reduccion bushing galvanizado de 25 mm a 19 mm',
    'Reduccion bushing galvanizado de 32 mm a 13 mm',
    'Reduccion bushing galvanizado de 32 mm a 19 mm',
    'Reduccion bushing galvanizado de 32 mm a 25 mm',
    'Reduccion bushing galvanizado de 38 mm a 13 mm',
    'Reduccion bushing galvanizado de 38 mm a 19 mm',
    'Reduccion bushing galvanizado de 38 mm a 25 mm',
    'Reduccion bushing galvanizado de 38 mm a 32 mm',
    'Reduccion bushing galvanizado de 51 mm a 13 mm',
    'Reduccion bushing galvanizado de 51 mm a 19 mm',
    'Reduccion bushing galvanizado de 51 mm a 25 mm',
    'Reduccion bushing galvanizado de 51 mm a 32 mm',
    'Reduccion bushing galvanizado de 51 mm a 38 mm',
    'Reduccion bushing galvanizado de 64 mm a 25 mm',
    'Reduccion bushing galvanizado de 64 mm a 32 mm',
    'Reduccion bushing galvanizado de 64 mm a 38 mm',
    'Reduccion bushing galvanizado de 64 mm a 51 mm',
    'Reduccion bushing galvanizado de 75 mm a 25 mm',
    'Reduccion bushing galvanizado de 75 mm a 32 mm',
    'Reduccion bushing galvanizado de 75 mm a 38 mm',
    'Reduccion bushing galvanizado de 75 mm a 51 mm',
    'Reduccion bushing galvanizado de 75 mm a 64 mm',
    'Reduccion bushing galvanizado de 100 mm a 25 mm',
    'Reduccion bushing galvanizado de 100 mm a 32 mm',
    'Reduccion bushing galvanizado de 100 mm a 38 mm',
    'Reduccion bushing galvanizado de 100 mm a 51 mm',
    'Reduccion bushing galvanizado de 100 mm a 64 mm',
    'Reduccion bushing galvanizado de 100 mm a 75 mm',
    'Reduccion bushing galvanizado de 150 mm a 51 mm',
    'Reduccion bushing galvanizado de 150 mm a 64 mm',
    'Reduccion bushing galvanizado de 150 mm a 75 mm',
    'Reduccion bushing galvanizado de 150 mm a 100 mm',
    'Reduccion campana galvanizada de 19 mm a  13 mm',
    'Reduccion campana galvanizada de 25 mm a 13 mm',
    'Reduccion campana galvanizada de 25 mm a  19 mm',
    'Reduccion campana galvanizada de 32 mm a  13 mm',
    'Reduccion campana galvanizada de 32 mm a  19 mm',
    'Reduccion campana galvanizada de 32 mm a  25 mm',
    'Reduccion campana galvanizada de 38 mm a  13 mm',
    'Reduccion campana galvanizada de 38 mm a  19 mm',
    'Reduccion campana galvanizada de 38 mm a 25 mm',
    'Reduccion campana galvanizada de 38 mm a 32 mm',
    'Reduccion campana galvanizada de 51 mm a 13 mm',
    'Reduccion campana galvanizada de 51 mm a 19 mm',
    'Reduccion campana galvanizada de 51 mm a 25 mm',
    'Reduccion campana galvanizada de 51 mm a 32 mm',
    'Reduccion campana galvanizada de 51 mm a 38 mm',
    'Reduccion campana galvanizada de 64 mm a 13 mm',
    'Reduccion campana galvanizada de 64 mm a 19 mm',
    'Reduccion campana galvanizada de 64 mm a 25 mm',
    'Reduccion campana galvanizada de 64 mm a 32 mm',
    'Reduccion campana galvanizada de 64 mm a 38 mm',
    'Reduccion campana galvanizada de 64 mm a 51 mm',
    'Reduccion campana galvanizada de 75 mm a 51 mm',
    'Reduccion campana galvanizada de 75 mm a 64 mm',
    'Reduccion campana galvanizada de 100 mm a 50 mm',
    'Reduccion campana galvanizada de 100 mm a 75 mm',
    'Reduccion campana galvanizada de 150 mm a 100 mm',
    'Codo galvanizado de 90 grados de 13 mm',
    'Codo galvanizado de 90 grados de 19 mm',
    'Codo galvanizado de 90 grados de 25 mm',
    'Codo galvanizado de 90 grados de 32 mm',
    'Codo galvanizado de 90 grados de 38 mm',
    'Codo galvanizado de 90 grados de 51 mm',
    'Codo galvanizado de 90 grados de 64 mm',
    'Codo galvanizado de 90 grados de 75 mm',
    'Codo galvanizado de 90 grados de 100 mm',
    'Codo galvanizado de 90 grados de 150 mm',
    'Codo galvanizado de 45 grados de 13 mm',
    'Codo galvanizado de 45 grados de 19 mm',
    'Codo galvanizado de 45 grados de 25 mm',
    'Codo galvanizado de 45 grados de 32 mm',
    'Codo galvanizado de 45 grados de 38 mm',
    'Codo galvanizado de 45 grados de 51 mm',
    'Codo galvanizado de 45 grados de 64 mm',
    'Codo galvanizado de 45 grados de 75 mm',
    'Codo galvanizado de 45 grados de 100 mm',
    'Tuerca union galvanizada de 13 mm',
    'Tuerca union galvanizada de 19 mm',
    'Tuerca union galvanizada de 25 mm',
    'Tuerca union galvanizada de 32 mm',
    'Tuerca union galvanizada de 38 mm',
    'Tuerca union galvanizada de 51 mm',
    'Tuerca union galvanizada de 64 mm',
    'Tuerca union galvanizada de 75 mm',
    'Tuerca union galvanizada de 100 mm',
    'Tee galvanizada de 13 mm',
    'Tee galvanizada de 19 mm',
    'Tee galvanizada de 25 mm',
    'Tee galvanizada de 32 mm',
    'Tee galvanizada de 38 mm',
    'Tee galvanizada de 51 mm',
    'Tee galvanizada de 64 mm',
    'Tee galvanizada de 75 mm',
    'Tee galvanizada de 100 mm',
    'Tee galvanizada de 150 mm',
    'Y galvanizada de 13 mm',
    'Y galvanizada de 19 mm',
    'Y galvanizada de 25 mm',
    'Y galvanizada de 32 mm',
    'Y galvanizada de 38 mm',
    'Y galvanizada de 51 mm',
    'Y galvanizada de 64 mm',
    'Y galvanizada de 75 mm',
    'Y galvanizada de 100 mm',
    'Cruz galvanizada de 13 mm',
    'Cruz galvanizada de 19 mm',
    'Cruz galvanizada de 25 mm',
    'Cruz galvanizada de 32 mm',
    'Cruz galvanizada de 38 mm',
    'Cruz galvanizada de 51 mm',
    'Cruz galvanizada de 64 mm',
    'Cruz galvanizada de 75 mm',
    'Cruz galvanizada de 100 mm',
    'Niple galvanizado de 1/2" x 5 cm de longitud',
    'Niple galvanizado de 1/2" x 7.5 cm de longitud',
    'Niple galvanizado de 3/4" x 5 cm de longitud',
    'Niple galvanizado de 1/2" x 10 cm de longitud',
    'Niple galvanizado de 3/4" x 10 cm de longitud',
    'Niple galvanizado de 1" x 10 cm de longitud',
    'Niple galvanizado de 1 1/4" x 10 cm de longitud',
    'Niple galvanizado de 1 1/2" x 10 cm de longitud',
    'Niple galvanizado de 2" x 10 cm de longitud',
    'Niple galvanizado de 2 1/2" x 10 cm de longitud',
    'Niple galvanizado de 3" x 10 cm de longitud',
    'Niple galvanizado de 4" x 10 cm de longitud',
    'Niple galvanizado de 1/2" x 15 cm de longitud',
    'Niple galvanizado de 3/4" x 15 cm de longitud',
    'Niple galvanizado de 1" x 15 cm de longitud',
    'Niple galvanizado de 1 1/4" x 15 cm de longitud',
    'Niple galvanizado de 1 1/2" x 15 cm de longitud',
    'Niple galvanizado de 2" x 15 cm de longitud',
    'Niple galvanizado de 2 1/2" x 15 cm de longitud',
    'Niple galvanizado de 3" x 15 cm de longitud',
    'Niple galvanizado de 4" x 15 cm de longitud',
    'Niple galvanizado de 1/2" x 20 cm de longitud',
    'Niple galvanizado de 3/4" x 20 cm de longitud',
    'Niple galvanizado de 1" x 20 cm de longitud',
    'Niple galvanizado de 1 1/4" x 20 cm de longitud',
    'Niple galvanizado de 1 1/2" x 20 cm de longitud',
    'Niple galvanizado de 2" x 20 cm de longitud',
    'Niple galvanizado de 2 1/2" x 20 cm de longitud',
    'Niple galvanizado de 3" x 20 cm de longitud',
    'Niple galvanizado de 4" x 20 cm de longitud',
    'Niple galvanizado de 1/2" x 25 cm de longitud',
    'Niple galvanizado de 3/4" x 25 cm de longitud',
    'Niple galvanizado de 1" x 25 cm de longitud',
    'Niple galvanizado de 1 1/4" x 25 cm de longitud',
    'Niple galvanizado de 1 1/2" x 25 cm de longitud',
    'Niple galvanizado de 2" x 25 cm de longitud',
    'Niple galvanizado de 2 1/2" x 25 cm de longitud',
    'Niple galvanizado de 3" x 25 cm de longitud',
    'Niple galvanizado de 4" x 25 cm de longitud',
    'Niple galvanizado de 1/2" x 30 cm de longitud',
    'Niple galvanizado de 3/4" x 30 cm de longitud',
    'Niple galvanizado de 1" x 30 cm de longitud',
    'Niple galvanizado de 1 1/4" x 30 cm de longitud',
    'Niple galvanizado de 1 1/2" x 30 cm de longitud',
    'Niple galvanizado de 2" x 30 cm de longitud',
    'Niple galvanizado de 2 1/2" x 30 cm de longitud',
    'Niple galvanizado de 3" x 30 cm de longitud',
    'Niple galvanizado de 4" x 30 cm de longitud',
    'Niple galvanizado cuerda corrida de 13 mm',
    'Niple galvanizado cuerda corrida de 19 mm',
    'Niple galvanizado cuerda corrida de 25 mm',
    'Niple galvanizado cuerda corrida de 32 mm',
    'Niple galvanizado cuerda corrida de 38 mm',
    'Niple galvanizado cuerda corrida de 51 mm',
    'Niple galvanizado cuerda corrida de 64 mm',
    'Niple galvanizado cuerda corrida de 75 mm',
    'Niple galvanizado cuerda corrida de 100 mm',
    'Niple galvanizado cuerda corrida de 150 mm',
    'Niple galvanizado de 1 1/2" x 0.50 mts',
    'Niple galvanizado de 1 1/2" x 0.70 mts',
    'Niple galvanizado de 1 1/2" x 1.00 mts',
    'Niple galvanizado de 2" x 0.50 mts',
    'Niple galvanizado de 2" x 0.70 mts',
    'Niple galvanizado de 2" x 1.00 mts',
    'Niple galvanizado de 2" x 1.50 mts',
    'Niple galvanizado de 2" x 2.00 mts',
    'Niple galvanizado de 2" x 2.50 mts',
    'Niple galvanizado de 2" x 3.00 mts',
    'Niple galvanizado de 3" x 0.50 mts',
    'Niple galvanizado de 3" x 0.70 mts',
    'Niple galvanizado de 3" x 1.00 mts',
    'Niple galvanizado de 3" x 1.50 mts',
    'Niple galvanizado de 3" x 2.00 mts',
    'Niple galvanizado de 3" x 2.50 mts',
    'Niple galvanizado de 3" x 3.00 mts',
    'Niple galvanizado de 4" x 0.50 mts',
    'Niple galvanizado de 4" x 0.70 mts',
    'Niple galvanizado de 4" x 1.00 mts',
    'Niple galvanizado de 4" x 1.50 mts',
    'Niple galvanizado de 4" x 2.00 mts',
    'Niple galvanizado de 4" x 2.50 mts',
    'Niple galvanizado de 4" x 3.00 mts',
    'Codo p.v.c. de 90° para alcantarillado de 150 mm',
    'Codo p.v.c. de 45° para alcantarillado de 150 mm',
    'Silleta p.v.c. para alcantarillado de 200 mm. x 150 mm',
    'Silleta p.v.c. para alcantarillado de 250 mm. x 150 mm',
    'Silleta p.v.c. para alcantarillado de 200 mm. x 100 mm',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 4" diam. c/ campana & empaque. norma nmx-e-241',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 6" diam. c/ campana & empaque.norma nmx-e-241',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 8" diam. c/ campana & empaque.norma nmx-e-241',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 10" diam. c/ campana & empaque. norma nmx-e-241',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 12" diam. c/ campana & empaque. norma nmx-e-241',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 15" diam. c/ campana & empaque. norma nmx-e-241',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 18" diam. c/ campana & empaque. norma nmx-e-241',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 24" diam. c/ campana & empaque. norma nmx-e-241',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 30" diam. c/ campana & empaque. norma nmx-e-241',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 36" diam. c/ campana & empaque. norma nmx-e-241',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 42" diam. c/ campana & empaque.  norma nmx-e-241',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 48" diam. c/ campana & empaque. norma nmx-e-241',
    'Tubo sanitario corrugado de polietileno de alta densidad tipo n-12, interior liso, de 60" diam. c/ campana & empaque.  norma nmx-e-241',
  ];
  //Sort names in ascending order
  let sortedNames = names.sort();
  
  //reference
  let input = document.getElementById("input_material");
  
  //Execute function on keyup
  input.addEventListener("keyup", (e) => {
    //loop through above array
    //Initially remove all elements ( so if user erases a letter or adds new letter then clean previous outputs)
    removeElements();
    for (let i of sortedNames) {
      //convert input to lowercase and compare with each string
  
      if (
        i.toLowerCase().startsWith(input.value.toLowerCase()) &&
        input.value != ""
      ) {
        //create li element
        let listItem = document.createElement("li");
        //One common class name
        listItem.classList.add("list-items");
        listItem.style.cursor = "pointer";
        listItem.setAttribute("onclick", "displayNames('" + i + "')");
        //Display matched part in bold
        let word = "<b>" + i.substr(0, input.value.length) + "</b>";
        word += i.substr(input.value.length);
        //display the value in array
        listItem.innerHTML = word;
        document.querySelector(".list").appendChild(listItem);
      }
    }
  });
  function displayNames(value) {
    input.value = value;
    removeElements();
  }
  function removeElements() {
    //clear all the item
    let items = document.querySelectorAll(".list-items");
    items.forEach((item) => {
      item.remove();
    });
  }